package com.quiz.AdaptiveQuiz.service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.quiz.AdaptiveQuiz.entity.AIQuestion;
import com.quiz.AdaptiveQuiz.entity.Difficulty;
import com.quiz.AdaptiveQuiz.entity.Subject;

@Service
public class OpenAIService {

    @Value("${openai.api.key}")
    private String apiKey;

    @Value("${openai.model}")
    private String model;

    private final RestTemplate restTemplate;
    private final com.quiz.AdaptiveQuiz.repository.QuestionRepository questionRepo;

    public OpenAIService(RestTemplate restTemplate, com.quiz.AdaptiveQuiz.repository.QuestionRepository questionRepo) {
        this.restTemplate = restTemplate;
        this.questionRepo = questionRepo;
    }

    public AIQuestion generateQuestion(Subject subject, Difficulty difficulty) {
        String prompt = """
                Generate one multiple-choice question (MCQ) with 4 options.
                Target Audience: CDAC / PG-DAC Students (Graduate Level CS).
                Subject: %s
                Difficulty: %s

                Requirements:
                1. Question should be conceptual and challenging (matches PG-DAC standard).
                2. Provide 4 distinct options.
                3. Clearly specify the correct answer.

                Return ONLY valid JSON in this format:
                { "question": "Question text here", "options": ["A", "B", "C", "D"], "correctAnswer": "Exact string of correct option" }
                """
                .formatted(subject.getName(), difficulty);

        Map<String, Object> body = new HashMap<>();
        body.put("model", model);
        body.put("messages", List.of(
                Map.of("role", "user", "content", prompt)));

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(apiKey);

        for (int i = 0; i < 3; i++) { // Retry up to 3 times
            try {
                ResponseEntity<Map> response = restTemplate.postForEntity(
                        "https://api.openai.com/v1/chat/completions",
                        new HttpEntity<>(body, headers),
                        Map.class);

                Map message = (Map) ((Map) ((List) response.getBody()
                        .get("choices")).get(0)).get("message");

                String content = message.get("content").toString();

                // Clean markdown if present
                content = content.replace("```json", "").replace("```", "").trim();

                ObjectMapper mapper = new ObjectMapper();
                AIQuestion q = mapper.readValue(content, AIQuestion.class);
                q.setSubject(subject);
                q.setDifficulty(difficulty);

                // Cache to DB
                try {
                    com.quiz.AdaptiveQuiz.entity.Question dbQ = new com.quiz.AdaptiveQuiz.entity.Question(
                            q.getQuestion(), q.getOptions(), q.getCorrectAnswer(), subject, difficulty);
                    questionRepo.save(dbQ);
                } catch (Exception e) {
                    System.err.println("Failed to cache question: " + e.getMessage());
                }

                System.out.println("✅ Question Generated by OpenAI");
                return q;
            } catch (org.springframework.web.client.HttpStatusCodeException e) {
                System.err.println("OpenAI API Error: " + e.getStatusCode() + " - " + e.getResponseBodyAsString());
            } catch (Exception e) {
                System.err.println("Attempt " + (i + 1) + " failed: " + e.getMessage());

                if (i == 2) {
                    System.err.println("AI Failed after 3 attempts.");
                    throw new RuntimeException("Failed to generate question from OpenAI");
                }
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ignored) {
                }
            }
        }
        throw new RuntimeException("Failed to generate question from OpenAI");
    }
}
